M48
; DRILL file {KiCad 8.0.6} date 2025-03-08T18:58:14-0800
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2025-03-08T18:58:14-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X6350Y62230
X6350Y6350
X72390Y62230
X72390Y6350
M30
